using System.ComponentModel.DataAnnotations;

namespace Rass.Api.Domain.Entities;

public class Contract
{
    public Guid Id { get; set; } = Guid.NewGuid();

    public Guid BuyerOrderId { get; set; }
    public BuyerOrder BuyerOrder { get; set; } = default!;

    public decimal AgreedPrice { get; set; }
    public decimal TotalValue { get; set; }
    public double TotalQuantityKg { get; set; }

    [MaxLength(40)]
    public string Status { get; set; } = "Draft"; // Draft, PendingSignature, Active, InDelivery, Completed, Disputed, Cancelled

    [MaxLength(100)]
    public string TrackingId { get; set; } = string.Empty;

    // === Contract Terms ===
    [MaxLength(500)]
    public string DeliveryTerms { get; set; } = string.Empty;

    [MaxLength(500)]
    public string PaymentTerms { get; set; } = string.Empty;

    [MaxLength(500)]
    public string PenaltyClause { get; set; } = string.Empty;
    
    [MaxLength(40)]
    public string ContractSource { get; set; } = "AutoGenerated"; // AutoGenerated, ManualUpload

    [MaxLength(200)]
    public string DocumentTitle { get; set; } = "Contract Agreement";

    [MaxLength(8000)]
    public string? DocumentContent { get; set; }

    public bool BuyerApproved { get; set; }
    public DateTime? BuyerApprovedAt { get; set; }

    public bool SellerApproved { get; set; }
    public DateTime? SellerApprovedAt { get; set; }

    public DateTime? DeliveryDeadline { get; set; }

    // === Digital Signature ===
    public bool BuyerSigned { get; set; }
    public DateTime? BuyerSignedAt { get; set; }

    [MaxLength(10)]
    public string? BuyerSignatureOtp { get; set; }

    public bool SellerSigned { get; set; }
    public DateTime? SellerSignedAt { get; set; }

    [MaxLength(10)]
    public string? SellerSignatureOtp { get; set; }

    // === Escrow Payment ===
    [MaxLength(40)]
    public string EscrowStatus { get; set; } = "None"; // None, Funded, Released, Disputed, Refunded

    public decimal EscrowAmount { get; set; }
    public DateTime? EscrowFundedAt { get; set; }
    public DateTime? EscrowReleasedAt { get; set; }

    [MaxLength(500)]
    public string? DisputeReason { get; set; }
    public DateTime? DisputedAt { get; set; }
    public Guid? DisputeResolvedBy { get; set; }
    public DateTime? DisputeResolvedAt { get; set; }

    [MaxLength(500)]
    public string? DisputeResolution { get; set; }

    // === Timestamps ===
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime? ActivatedAt { get; set; }
    public DateTime? CompletedAt { get; set; }

    // === Relations ===
    public ICollection<ContractLot> ContractLots { get; set; } = new List<ContractLot>();
    public ICollection<TransportRequest> TransportRequests { get; set; } = new List<TransportRequest>();
    public ICollection<StorageBooking> StorageBookings { get; set; } = new List<StorageBooking>();
    public ICollection<PaymentLedger> PaymentLedgers { get; set; } = new List<PaymentLedger>();
}

public class ContractLot
{
    public Guid ContractId { get; set; }
    public Contract Contract { get; set; } = default!;

    public Guid LotId { get; set; }
    public Lot Lot { get; set; } = default!;
}

